# Generated by Django 5.1 on 2025-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('capacidade', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('M', 'Matutino'), ('T', 'Tarde'), ('N', 'Noturno'), ('S', 'Integral')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('tipo_curso', models.CharField(choices=[('CT', 'Curso Técnico'), ('CAI', 'Curso de Aprendizagem Industrial'), ('CS', 'Curso Superior'), ('FIC', 'Formação Inicial Continuada')], max_length=5)),
                ('hora_aula', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('turma', models.CharField(max_length=255)),
            ],
        ),
    ]
